on:
  workflow_call:
    inputs:
      word-to-print:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
    outputs:
      resuable-return: 
        description: "just output of a value"
        value: "${{ jobs.reusable_workflow_job.outputs.resuable-return }}"
      


jobs:

  print-pre-requisite:
    runs-on: ubuntu-latest

    steps:
      - name: Print pre-requisites
        run: echo HEllO

  reusable_workflow_job:
    runs-on: ubuntu-latest
    outputs:
      resuable-return: ${{ steps.output-set.outputs.myVar }}
    # environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.envPAT }}
      
      - run: echo "${{ inputs.word-to-print }}"

      - id: output-set
        run: echo "myVar=$(echo helloTest)" >> GITHUB_OUTPUT
