on:
  workflow_call:
    inputs:
      word-to-print:
        required: true
        type: string
    # secrets:
    #   envPAT:
    #     required: true


jobs:

  print-pre-requisite:
    runs-on: ubuntu-latest

    steps:
      - name: Print pre-requisites
        run: echo ${{ inputs.word-to-print }}

  reusable_workflow_job:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.envPAT }}
      
      - run: echo ${{ inputs.word-to-print }}
