# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    # environment: production
    steps:
    - name: Echo Hello World
      run: echo Hello World

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
