on:
  workflow_dispatch:

jobs:

  print-pre-requisite:
    runs-on: ubuntu-latest

    steps:
    #   - name: Print pre-requisites
    #     run: echo ${{ secrets }}
      # - uses: actions/github-script@v7
      #   id: set-result
      #   with:
      #     script: |
      #       console.log(github);

      - name: Test variable
        run: echo "${{ vars.TEST_VAR }}"

      - name: Print name from variable
        run: echo "${{ vars.TEST_VAR }}" | jq -r '.name'
